AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MicroserviceCfnUrl:
    Type: String
    Description: 'S3 Object URL for CFN Template for all attached microservices'
  CertificateArn:
    Type: String
    Description: 'ARN of Associated ACM Certificate for all associated subdomains domain'
  Domain:
    Type: String
    Description: 'Eg: example.com'
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  S3ArtifactsBucketArn:
    Type: 'String'
    Description: 'ARN of S3 Bucket being used for storing artifacts'
  S3ArtifactsServicePolicy:
    Type: 'String'
    Description: 'ARN of IAM Policy with write permissions into S3 Artifacts Bucket'
  

Resources: 
  Microservice1:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters: 
        CertificateArn: !Ref CertificateArn
        Domain: !Ref Domain
        HostedZoneId: !Ref HostedZoneId
        S3ArtifactsBucketArn: !Ref S3ArtifactsBucketArn
        S3ArtifactsServicePolicy: !Ref S3ArtifactsServicePolicy
        EnvironmentName: 'prod'
        GitBranch: 'prod'
        GitRepository: 'https://github.com/....git'
        Subdomain: 'common-api'
      TemplateURL: !Ref MicroserviceCfnUrl
