AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          exports.handler =  async function(event, context) {
            console.log("EVENT: \n" + JSON.stringify(event, null, 2))
            return context.logStreamName
          }
      FunctionName: !Sub '${Subdomain}-${EnvironmentName}'
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt LambdaIAMRole.Arn
  APIGatewayRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${Subdomain}-${EnvironmentName}'
    DependsOn:
      - LambdaFunction
  APIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt APIGatewayRestAPI.RootResourceId
      PathPart: !Sub '${Subdomain}-${EnvironmentName}'
    DependsOn:
      - APIGatewayRestAPI
  APIGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref APIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations'
          - LambdaFuncNameArn: !GetAtt LambdaFunction.Arn
    DependsOn:
      - APIGatewayResource
  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      StageName:
        Ref: EnvironmentName
    DependsOn:
      - APIGatewayMethod
  APIGatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - APIGatewayDeployment
  LambdaIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda-service-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LambdaCloudWatchLogGroupName}:log-stream:${Subdomain}.${Domain}-${EnvironmentName}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LambdaCloudWatchLogGroupName}'
  CodeBuildIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref S3ArtifactsServicePolicy
      Policies:
        - PolicyName: !Sub 'codebuild-service-role-${Subdomain}-${EnvironmentName}'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:UpdateFunctionCode"
                  - "lambda:GetFunction"
                  - "lambda:PutProvisionedConcurrencyConfig"
                  - "lambda:DeleteAlias"
                  - "lambda:PublishVersion"
                  - "lambda:DeleteFunctionConcurrency"
                  - "lambda:GetAlias"
                  - "lambda:UpdateAlias"
                  - "lambda:CreateAlias"
                  - "lambda:PutFunctionConcurrency"
                Resource: 
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Subdomain}-${EnvironmentName}'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Subdomain}-${EnvironmentName}:*'
    DependsOn:
      - LambdaFunction
  CloudWatchLogStream:
    Type: 'AWS::Logs::LogStream'
    Properties:
      LogGroupName: !Ref LambdaCloudWatchLogGroupName
      LogStreamName: !Sub '${Subdomain}.${Domain}-${EnvironmentName}'
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${Subdomain}-${EnvironmentName}'
      ServiceRole: !Ref CodeBuildIAMRole
      Artifacts:
        Type: S3
        Location: !Ref S3ArtifactsBucketName
        Packaging: ZIP
        Path: !Sub 'backend/${Subdomain}-${EnvironmentName}'
        NamespaceType: BUILD_ID
        Name: 'artifact.zip'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        EnvironmentVariables:
          - Name: lambda_name
            Type: PLAINTEXT
            Value: !Sub '${Subdomain}-${EnvironmentName}'
      Source:
        Type: GITHUB
        Location: !Ref GitRepository
        ReportBuildStatus: true
      Triggers:
        BuildType: BUILD
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_MERGED
            - Type: BASE_REF
              Pattern: !Sub '^refs/heads/${GitBranch}$'
              ExcludeMatchedPattern: false

Parameters:
  Domain:
    Type: String
    Description: 'Eg: example.com'
  Subdomain:
    Type: String
    Description: 'Only prefix. Eg: api, dev, dev-api, beta'
  EnvironmentName:
    Type: String
    Default: Prod
  GitRepository:
    Type: String
    Description: 'HTTPS clone URL to the repository (Must have OAuth access setup *with Organization access, if repository is in an organization*)'
  GitBranch:
    Type: String
    Description: 'Name of branch to be deployed'
  LambdaCloudWatchLogGroupName:
    Type: String
    Default: lambda-execution-logs
  S3ArtifactsBucketName:
    Type: 'String'
    Description: 'ARN of S3 Bucket being used for storing artifacts'
  S3ArtifactsServicePolicy:
    Type: 'String'
    Description: 'ARN of IAM Policy with write permissions into S3 Artifacts Bucket'
Outputs:
  RestApiArn: 
    Value: !Ref APIGatewayRestAPI
    Description: ARN of created RestApi
